# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- powershell: |
    choco install docfx -y
    docfx docfx.json
    if ($lastexitcode -ne 0){
      throw ("Error generating document")
    }
- task: ArchiveFiles@2
  displayName: 'Archive _site'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/_site/'
    includeRootFolder: false
    archiveFile: release.zip
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'